services:

  adminer_core:
    image: adminer
    restart: always
    ports:
      - 8085:8080

  db:
        image: "mcr.microsoft.com/mssql/server:2017-latest"
        environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=1Secure*Password1

  dbmysql:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example